# Generated by Django 3.2.8 on 2021-10-24 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CncProg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('plastic', 'Plastic Material'), ('plexiglas', 'Plexiglas Material'), ('wood', 'Wood Material'), ('non-ferrous metal', 'Non-ferrous Metal Material'), ('aluminium', 'Aluminium Material'), ('magnesium', 'Magnesium Material'), ('steel', 'Steel Material'), ('cast iron', 'Cast Iron Material'), ('titanium', 'Titanium Material')], default='plastic', max_length=20)),
                ('teeth_numbers', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six')], default='one')),
                ('cutter_diameter', models.FloatField(choices=[(0.3, '0.3'), (0.4, '0.4'), (0.5, '0.5'), (0.6, '0.6'), (0.7, '0.7'), (0.8, '0.8'), (0.9, '0.9'), (1.0, '1.0'), (1.1, '1.1'), (1.2, '1.2'), (1.3, '1.3'), (1.4, '1.4'), (1.5, '1.5'), (1.6, '1.6'), (1.7, '1.7'), (1.8, '1.8'), (1.9, '1.9'), (2.0, '2.0'), (2.1, '2.1'), (2.2, '2.2'), (2.3, '2.3'), (2.4, '2.4'), (2.5, '2.5'), (2.6, '2.6'), (2.7, '2.7'), (2.8, '2.8'), (2.9, '2.9'), (3.0, '3.0'), (3.1, '3.1'), (3.2, '3.2'), (3.3, '3.3'), (3.4, '3.4'), (3.5, '3.5'), (3.6, '3.6'), (3.7, '3.7'), (3.8, '3.8'), (3.9, '3.9'), (4.0, '4.0'), (4.1, '4.1'), (4.2, '4.2'), (4.3, '4.3'), (4.4, '4.4'), (4.5, '4.5'), (4.6, '4.6'), (4.7, '4.7'), (4.8, '4.8'), (4.9, '4.9'), (5.0, '5.0'), (5.1, '5.1'), (5.2, '5.2'), (5.3, '5.3'), (5.4, '5.4'), (5.5, '5.5'), (5.6, '5.6'), (5.7, '5.7'), (5.8, '5.8'), (5.9, '5.9'), (6.0, '6.0'), (6.1, '6.1'), (6.2, '6.2'), (6.3, '6.3'), (6.4, '6.4'), (6.5, '6.5'), (6.6, '6.6'), (6.7, '6.7'), (6.8, '6.8'), (6.9, '6.9'), (7.0, '7.0'), (7.1, '7.1'), (7.2, '7.2'), (7.3, '7.3'), (7.4, '7.4'), (7.5, '7.5'), (7.6, '7.6'), (7.7, '7.7'), (7.8, '7.8'), (7.9, '7.9'), (8.0, '8.0'), (8.1, '8.1'), (8.2, '8.2'), (8.3, '8.3'), (8.4, '8.4'), (8.5, '8.5'), (8.6, '8.6'), (8.7, '8.7'), (8.8, '8.8'), (8.9, '8.9'), (9.0, '9.0'), (9.1, '9.1'), (9.2, '9.2'), (9.3, '9.3'), (9.4, '9.4'), (9.5, '9.5'), (9.6, '9.6'), (9.7, '9.7'), (9.8, '9.8'), (9.9, '9.9'), (10.0, '10.0')], default='2.0')),
                ('cut_speed_min', models.IntegerField()),
                ('cut_speed_max', models.IntegerField()),
                ('feed_per_tooth', models.FloatField()),
                ('spindel_speed_min', models.IntegerField()),
                ('spindel_speed_max', models.IntegerField()),
                ('moving_speed_min', models.IntegerField()),
                ('moving_speed_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InformationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyCutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('Plastic', 'Plastic Material'), ('Plexiglas', 'Plexiglas Material'), ('Wood', 'Wood Material'), ('Non-ferrous metal', 'Non-ferrous Metal Material'), ('Aluminium', 'Aluminium Material'), ('Magnesium', 'Magnesium Material'), ('Steel', 'Steel Material'), ('Cast iron', 'Cast Iron Material'), ('Titanium', 'Titanium Material')], default='plastic', max_length=20)),
                ('teeth_numbers', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six')], default='one')),
                ('cutter_diameter', models.FloatField(choices=[(0.3, '0.3'), (0.4, '0.4'), (0.5, '0.5'), (0.6, '0.6'), (0.7, '0.7'), (0.8, '0.8'), (0.9, '0.9'), (1.0, '1.0'), (1.1, '1.1'), (1.2, '1.2'), (1.3, '1.3'), (1.4, '1.4'), (1.5, '1.5'), (1.6, '1.6'), (1.7, '1.7'), (1.8, '1.8'), (1.9, '1.9'), (2.0, '2.0'), (2.1, '2.1'), (2.2, '2.2'), (2.3, '2.3'), (2.4, '2.4'), (2.5, '2.5'), (2.6, '2.6'), (2.7, '2.7'), (2.8, '2.8'), (2.9, '2.9'), (3.0, '3.0'), (3.1, '3.1'), (3.2, '3.2'), (3.3, '3.3'), (3.4, '3.4'), (3.5, '3.5'), (3.6, '3.6'), (3.7, '3.7'), (3.8, '3.8'), (3.9, '3.9'), (4.0, '4.0'), (4.1, '4.1'), (4.2, '4.2'), (4.3, '4.3'), (4.4, '4.4'), (4.5, '4.5'), (4.6, '4.6'), (4.7, '4.7'), (4.8, '4.8'), (4.9, '4.9'), (5.0, '5.0'), (5.1, '5.1'), (5.2, '5.2'), (5.3, '5.3'), (5.4, '5.4'), (5.5, '5.5'), (5.6, '5.6'), (5.7, '5.7'), (5.8, '5.8'), (5.9, '5.9'), (6.0, '6.0'), (6.1, '6.1'), (6.2, '6.2'), (6.3, '6.3'), (6.4, '6.4'), (6.5, '6.5'), (6.6, '6.6'), (6.7, '6.7'), (6.8, '6.8'), (6.9, '6.9'), (7.0, '7.0'), (7.1, '7.1'), (7.2, '7.2'), (7.3, '7.3'), (7.4, '7.4'), (7.5, '7.5'), (7.6, '7.6'), (7.7, '7.7'), (7.8, '7.8'), (7.9, '7.9'), (8.0, '8.0'), (8.1, '8.1'), (8.2, '8.2'), (8.3, '8.3'), (8.4, '8.4'), (8.5, '8.5'), (8.6, '8.6'), (8.7, '8.7'), (8.8, '8.8'), (8.9, '8.9'), (9.0, '9.0'), (9.1, '9.1'), (9.2, '9.2'), (9.3, '9.3'), (9.4, '9.4'), (9.5, '9.5'), (9.6, '9.6'), (9.7, '9.7'), (9.8, '9.8'), (9.9, '9.9'), (10.0, '10.0')], default='2.0')),
                ('spindel_speed', models.IntegerField()),
                ('moving_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='user/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('note', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cncapp.informationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cncapp.information')),
            ],
        ),
    ]
