# Generated by Django 3.2.8 on 2021-10-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cutters/%Y/%m/%d/'),
        ),
    ]
